---@class AdwaitaPalette
---@field blue_1 string
---@field blue_2 string
---@field blue_3 string
---@field blue_4 string
---@field blue_5 string
---@field blue_6 string
---@field blue_7 string
---@field brown_1 string
---@field brown_2 string
---@field brown_3 string
---@field brown_4 string
---@field brown_5 string
---@field chameleon_3 string
---@field dark_1 string
---@field dark_2 string
---@field dark_3 string
---@field dark_4 string
---@field dark_5 string
---@field dark_6 string
---@field green_1 string
---@field green_2 string
---@field green_3 string
---@field green_4 string
---@field green_5 string
---@field green_6 string
---@field green_7 string
---@field light_1 string
---@field light_2 string
---@field light_3 string
---@field light_4 string
---@field light_5 string
---@field light_6 string
---@field light_7 string
---@field orange_1 string
---@field orange_2 string
---@field orange_3 string
---@field orange_4 string
---@field orange_5 string
---@field purple_1 string
---@field purple_2 string
---@field purple_3 string
---@field purple_4 string
---@field purple_5 string
---@field red_1 string
---@field red_2 string
---@field red_3 string
---@field red_4 string
---@field red_5 string
---@field teal_1 string
---@field teal_2 string
---@field teal_3 string
---@field teal_4 string
---@field teal_5 string
---@field violet_2 string
---@field violet_3 string
---@field violet_4 string
---@field yellow_1 string
---@field yellow_2 string
---@field yellow_3 string
---@field yellow_4 string
---@field yellow_5 string
---@field yellow_6 string
---@field libadwaita_dark_1 string
---@field libadwaita_dark_2 string
---@field libadwaita_dark_3 string
---@field libadwaita_dark_4 string
---@field libadwaita_dark_5 string
---@field libadwaita_dark_6 string
---@field libadwaita_dark_7 string
---@field none "NONE"
return {
    -- Source: https://gitlab.gnome.org/GNOME/gtksourceview/-/blob/master/data/styles/Adwaita.xml
    -- Licensed under LGPL-2.1-or-later
    blue_1	            = "#99C1F1",
    blue_2	            = "#62A0EA",
    blue_3	            = "#3584E4",
    blue_4	            = "#1C71D8",
    blue_5	            = "#1A5FB4",
    blue_6	            = "#1B497E",
    blue_7	            = "#193D66",
    brown_1	            = "#CDAB8F",
    brown_2	            = "#B5835A",
    brown_3	            = "#986A44",
    brown_4	            = "#865E3C",
    brown_5	            = "#63452C",
    chameleon_3         = "#4E9A06",
    dark_1	            = "#77767B",
    dark_2	            = "#5E5C64",
    dark_3	            = "#504E55",
    dark_4	            = "#3D3846",
    dark_5	            = "#241F31",
    dark_6	            = "#000000",
    green_1	            = "#8FF0A4",
    green_2	            = "#57E389",
    green_3	            = "#33D17A",
    green_4	            = "#2EC27E",
    green_5	            = "#26A269",
    green_6	            = "#1F7F56",
    green_7	            = "#1C6849",
    light_1	            = "#FFFFFF",
    light_2	            = "#FCFCFC",
    light_3	            = "#F6F5F4",
    light_4	            = "#DEDDDA",
    light_5	            = "#C0BFBC",
    light_6	            = "#B0AFAC",
    light_7	            = "#9A9996",
    orange_1            = "#FFBE6F",
    orange_2            = "#FFA348",
    orange_3            = "#FF7800",
    orange_4            = "#E66100",
    orange_5            = "#C64600",
    purple_1            = "#DC8ADD",
    purple_2            = "#C061CB",
    purple_3            = "#9141AC",
    purple_4            = "#813D9C",
    purple_5            = "#613583",
    red_1               = "#F66151",
    red_2               = "#ED333B",
    red_3               = "#E01B24",
    red_4               = "#C01C28",
    red_5               = "#A51D2D",
    teal_1              = "#93DDC2",
    teal_2              = "#5BC8AF",
    teal_3              = "#33B2A4",
    teal_4              = "#26A1A2",
    teal_5              = "#218787",
    violet_2            = "#7D8AC7",
    violet_3            = "#6362C8",
    violet_4            = "#4E57BA",
    yellow_1            = "#F9F06B",
    yellow_2            = "#F8E45C",
    yellow_3            = "#F6D32D",
    yellow_4            = "#F5C211",
    yellow_5            = "#E5A50A",
    yellow_6            = "#D38B09",
    libadwaita_dark_1   = "#1D1D20",
    libadwaita_dark_2   = "#222226",
    libadwaita_dark_3   = "#252529",
    libadwaita_dark_4   = "#28282C",
    libadwaita_dark_5   = "#2E2E32",
    libadwaita_dark_6   = "#303036",
    libadwaita_dark_7   = "#36363A",
    none                = "NONE"
}
